載入 NumPy

In [1]:
import numpy as np

目前安裝的版本

In [2]:
np.__version__

'1.19.5'

作業目標:
在array中，可以靈活應用索引幫助資料擷取
作業重點:
陣列的索引、切片、以及屬性，皆需要注意使用方式
陣列之中索引式由0開始請同學注意

題目:

1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

2.呈上題，將以上數列取出偶數。

3.呈1題，將數列取出3的倍數。


In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
# 2.呈上題，將以上數列取出偶數。
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# 3.呈1題，將數列取出3的倍數。
a[::3]

array([ 0,  3,  6,  9, 12, 15, 18])